name: moodcast
description: "A Flutter project For Detect Your Mood Based On The Weather ."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.8.0+1
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_it: ^8.0.3
  google_sign_in: ^6.3.0
  lucide_icons_flutter: ^3.0.0
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.3
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lotties/
    - assets/weather/
    - assets/icon/

  fonts:
    - family: Amiga
      fonts:
        - asset: assets/fonts/AmigaRounded.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
