// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvR2wq7kAOE6WFoxA6iqRWmj3RPAlKMc',
    appId: '1:718230045100:web:24358e20a41e48a726fa09',
    messagingSenderId: '718230045100',
    projectId: 'mfk-2f025',
    authDomain: 'mfk-2f025.firebaseapp.com',
    storageBucket: 'mfk-2f025.firebasestorage.app',
    measurementId: 'G-3BR0LXHLD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4jJET-gV-EDXmVpCH64jgPc3XRBrUNzI',
    appId: '1:718230045100:android:4380b2ddb84c191326fa09',
    messagingSenderId: '718230045100',
    projectId: 'mfk-2f025',
    storageBucket: 'mfk-2f025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBvR2wq7kAOE6WFoxA6iqRWmj3RPAlKMc',
    appId: '1:718230045100:web:8c8ffc33e46d586f26fa09',
    messagingSenderId: '718230045100',
    projectId: 'mfk-2f025',
    authDomain: 'mfk-2f025.firebaseapp.com',
    storageBucket: 'mfk-2f025.firebasestorage.app',
    measurementId: 'G-WL2SRZ1SB0',
  );
}
